[settings]
experimental = true

[tools]
pnpm = "latest"
glab = "latest"
helm = "latest"
java = "temurin-21.0.2+13.0.LTS"
gleam = "latest"
erlang = "latest"
go = "latest"
just = "latest"
postgres = "15"
zoxide = "latest"
kn = "1.6.0"
kubie = "0.17.2"
fzf = "0.32.0"
nodejs = "18.18.2"
deno = "1.25.2"
bun = "latest"
rust = "stable"
sops = "3.7.3"
age = "1.1.1"
istioctl = "latest"
node = "18.19.1"
cue = "0.10.0"
awscli = "2.15.25"
skaffold = "latest"
pre-commit = "latest"
kubectl = "latest"
krew = "latest"
quarkus = "latest"
python = "3.13.0"

